import mod.server.extraServerApi as serverApi
compServer = serverApi.GetEngineCompFactory()
levelId = serverApi.GetLevelId()

class LevelServer:
    game = compServer.CreateGame(levelId)
    chunkSource = compServer.CreateChunkSource(levelId)
    achievement = compServer.CreateAchievement(levelId)
    biome = compServer.CreateBiome(levelId)
    dimension = compServer.CreateDimension(levelId)
    blockInfo = compServer.CreateBlockInfo(levelId)
    weather = compServer.CreateWeather(levelId)
    time = compServer.CreateTime(levelId)
    block = compServer.CreateBlock(levelId)
    blockEntity = compServer.CreateBlockEntity(levelId)
    blockEntityData = compServer.CreateBlockEntityData(levelId)
    blockState = compServer.CreateBlockState(levelId)
    blockUseEventWhiteList = compServer.CreateBlockUseEventWhiteList(levelId)
    message = compServer.CreateMsg(levelId)
    command = compServer.CreateCommand(levelId)
    chestBlock = compServer.CreateChestBlock(levelId)
    explosion = compServer.CreateExplosion(levelId)
    extraData = compServer.CreateExtraData(levelId)
    feature = compServer.CreateFeature(levelId)
    itemBanned = compServer.CreateItemBanned(levelId)
    mobSpawn = compServer.CreateMobSpawn(levelId)
    projectile = compServer.CreateProjectile(levelId)
    portal = compServer.CreatePortal(levelId)
    recipe = compServer.CreateRecipe(levelId)
    redstone = compServer.CreateRedStone(levelId)
